INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('11', 'Rondônia','RO',' Região Norte', 52);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('12', 'Acre','AC',' Região Norte', 22);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('13', 'Amazonas','AM',' Região Norte', 62);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('14', 'Roraima','RR',' Região Norte', 15);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('15', 'Pará','PA',' Região Norte', 144);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('16', 'Amapá','AP',' Região Norte', 16);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('17', 'Tocantins','TO',' Região Norte', 139);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('21', 'Maranhão','MA',' Região Nordeste', 217);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('22', 'Piauí','PI',' Região Nordeste', 224);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('23', 'Ceará','CE',' Região Nordeste', 184);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('24', 'Rio Grande do Norte','RN',' Região Nordeste', 167);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('25', 'Paraíba','PB',' Região Nordeste', 223);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('26', 'Pernambuco','PE',' Região Nordeste', 185);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('27', 'Alagoas','AL',' Região Nordeste', 102);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('28', 'Sergipe','SE',' Região Nordeste', 75);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('29', 'Bahia','BA',' Região Nordeste', 417);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('31', 'Minas Gerais','MG',' Região Sudeste', 853);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('32', 'Espírito Santo','ES',' Região Sudeste', 78);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('33', 'Rio de Janeiro','RJ',' Região Sudeste', 92);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('35', 'São Paulo','SP',' Região Sudeste', 645);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('41', 'Paraná','PR',' Região Sul', 399);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('42', 'Santa Catarina','SC',' Região Sul', 295);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('43', 'Rio Grande do Sul','RS',' Região Sul', 497);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('50', 'Mato Grosso do Sul','MS',' Região Centro-Oeste', 79);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('51', 'Mato Grosso','MT',' Região Centro-Oeste', 141);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('52', 'Goiás','GO',' Região Centro-Oeste', 246);
INSERT INTO unidadesFederacao (cod_ibge, estado, uf, regiao, num_municipios) VALUES ('53', 'Distrito Federal','DF',' Região Centro-Oeste', 1);
